language: python
sudo: False
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- nightly # 3.6
env:
  matrix:
  - DJANGO="1.7"
  - DJANGO="1.8"
  - DJANGO="1.9"

install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install "django==$DJANGO"

#Django version	Python versions
#1.8	          2.7, 3.2 (until the end of 2016), 3.3, 3.4, 3.5
#1.9, 1.10      2.7, 3.4, 3.5
matrix:
  exclude:
    # Django 1.9+ no longer supports python 3.2/3.3
  - python: 3.3
    env: DJANGO="1.9"

  # django 1.7 isn't supported on python > 3.4
  - python: 3.5
    env: DJANGO="1.7"
  - python: nightly
    env: DJANGO="1.7"

script: make travis

after_success:
- coveralls
